/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.fvgprinc.app.jpadron2.ui;

import com.fvgprinc.app.jpadron2.be.PadronElecBE;
import com.fvgprinc.app.jpadron2.bl.PadronElecBL;
import com.fvgprinc.tools.common.datalayer.CommonDALExceptions;
import com.fvgprinc.tools.common.string.MyCommonString;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.InputStreamReader;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author garfi
 */
public class JFrmLoadPadron2 extends javax.swing.JFrame {

    final static org.apache.log4j.Logger logger = org.apache.log4j.Logger.getLogger(JFrmLoadPadron2.class);

    /**
     * Creates new form JFrmLoadPadron2
     */
    public JFrmLoadPadron2() {
        initComponents();
        initMyComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButCargarPadron = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTxtFileName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTxtPath = new javax.swing.JTextField();
        jButBuscar = new javax.swing.JButton();
        jTxtFldNumCedula = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButCargarPadron.setText("Cargar Padron");
        jButCargarPadron.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButCargarPadronActionPerformed(evt);
            }
        });

        jLabel1.setText("Archivo:");

        jLabel2.setText("Path:");

        jButBuscar.setText("Buscar");
        jButBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTxtFileName)
                            .addComponent(jTxtPath)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(272, 272, 272)
                                .addComponent(jButCargarPadron))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jTxtFldNumCedula, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButBuscar)))
                        .addGap(0, 279, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButBuscar)
                    .addComponent(jTxtFldNumCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTxtPath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTxtFileName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButCargarPadron)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cargarPadron(String pathFile, String fname) throws SQLException, IOException, CommonDALExceptions {
        PadronElecBL pebl = new PadronElecBL();

        PadronElecBE pebe = new PadronElecBE();

        int i = 0;
        boolean finCarga = false;

        fname = pathFile + File.separator + fname;

        pebl.deleteAll();

        File fi = new File(fname);
        FileInputStream fis = new FileInputStream(fi);
        // Charset charset = Charset.forName("UTF-16");
        InputStreamReader isr = new InputStreamReader(fis, "UTF8");
        String en = isr.getEncoding();
        try (BufferedReader br = new BufferedReader(isr)) {
            // <editor-fold defaultstate="collapsed" desc=" Buffered-reader ">
            String line = MyCommonString.EMPTYSTR;
            while ((line = br.readLine()) != null) {
                String[] scrap = line.split(",", 7);
                pebe.setCedula(scrap[0].trim());
                pebe.setCodElect(scrap[1].trim());
                pebe.setFecCaduca(scrap[2].trim());
                pebe.setNombre(scrap[4].trim());
                pebe.setApellido1(scrap[5].trim());
                pebe.setApellido2(scrap[6].trim());
                pebl.insertar(pebe);
            }
        } catch (Exception ex) {
            logger.fatal(ex.toString(), ex);
        }

        JOptionPane.showConfirmDialog(null, "Proceso Finalizado....!");

    }


    private void jButCargarPadronActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButCargarPadronActionPerformed
        try {
            cargarPadron(jTxtPath.getText(), jTxtFileName.getText());
        } catch (SQLException ex) {
            Logger.getLogger(JFrmLoadPadron2.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(JFrmLoadPadron2.class.getName()).log(Level.SEVERE, null, ex);
        } catch (CommonDALExceptions ex) {
            Logger.getLogger(JFrmLoadPadron2.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButCargarPadronActionPerformed

    private void jButBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButBuscarActionPerformed
        String msg;
        try {
            PadronElecBL pebl = new PadronElecBL();
            if (pebl.existe(jTxtFldNumCedula.getText())) {
                msg = "Existe!!!!!.....";
            } else {
                msg = "NO Existe!!!!!.....";
            }
            JOptionPane.showMessageDialog(null, msg);

        } catch (SQLException ex) {
            Logger.getLogger(JFrmLoadPadron2.class.getName()).log(Level.SEVERE, null, ex);
        } catch (CommonDALExceptions ex) {
            Logger.getLogger(JFrmLoadPadron2.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jButBuscarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrmLoadPadron2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrmLoadPadron2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrmLoadPadron2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrmLoadPadron2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JFrmLoadPadron2 jfrm = new JFrmLoadPadron2();
                jfrm.setTitle("Cargar Padron");
                jfrm.setLocationRelativeTo(null);
                jfrm.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButBuscar;
    private javax.swing.JButton jButCargarPadron;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jTxtFileName;
    private javax.swing.JTextField jTxtFldNumCedula;
    private javax.swing.JTextField jTxtPath;
    // End of variables declaration//GEN-END:variables

    private void initMyComponents() {
        jTxtPath.setText("C:\\Users\\garfi\\Downloads\\padron_completo");
        jTxtFileName.setText("PADRON_COMPLETO.txt");

    }
}
