/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.fvgprinc.app.jpadron2.ui;

import com.fvgprinc.app.jpadron2.be.PadronElecBE;
import com.fvgprinc.app.jpadron2.bl.CargadorArchivos;
import com.fvgprinc.app.jpadron2.bl.PadronElecBL;
import com.fvgprinc.app.jpadron2.globals.GloblaConstants;
import com.fvgprinc.app.jpadron2.model.PadronElecTableModel;
import com.fvgprinc.tools.db.CommonDALExceptions;
import com.fvgprinc.tools.db.DIContainer;
import com.fvgprinc.tools.db.ParamAction;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.InputStreamReader;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.AbstractTableModel;

/**
 *
 * @author garfi
 */
public class JFrmLoadPadron2 extends javax.swing.JFrame {

    final static org.apache.log4j.Logger logger = org.apache.log4j.Logger.getLogger(JFrmLoadPadron2.class);

    CargadorArchivos ca;
    boolean isStarted;

    /**
     * Creates new form JFrmLoadPadron2
     */
    public JFrmLoadPadron2() {
        initComponents();
        initMyComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPnlCarga = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTxtPath = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jTxtFileName = new javax.swing.JTextField();
        jButCargarPadron = new javax.swing.JButton();
        jButCargarPadronAsync = new javax.swing.JButton();
        jButCancelCargAsync = new javax.swing.JButton();
        jPBarLoadFile = new javax.swing.JProgressBar();
        jPnlSearch = new javax.swing.JPanel();
        jTblSearch = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jTxtFldNumCedula = new javax.swing.JTextField();
        jButBuscar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jTxtFldNombre = new javax.swing.JTextField();
        jTxtFldPrimApe = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTxtFldSegApe = new javax.swing.JTextField();
        jButBuscar1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTblData = new javax.swing.JTable();
        jToolBar1 = new javax.swing.JToolBar();
        jBtnExit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setText("Path:");

        jLabel1.setText("Archivo:");

        jButCargarPadron.setText("Cargar Padron");
        jButCargarPadron.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButCargarPadronActionPerformed(evt);
            }
        });

        jButCargarPadronAsync.setText("Cargar Padron Asincrono");
        jButCargarPadronAsync.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButCargarPadronAsyncActionPerformed(evt);
            }
        });

        jButCancelCargAsync.setText("Cancelarr Padron Asincrono");
        jButCancelCargAsync.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButCancelCargAsyncActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPnlCargaLayout = new javax.swing.GroupLayout(jPnlCarga);
        jPnlCarga.setLayout(jPnlCargaLayout);
        jPnlCargaLayout.setHorizontalGroup(
            jPnlCargaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnlCargaLayout.createSequentialGroup()
                .addGroup(jPnlCargaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPnlCargaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPnlCargaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTxtFileName)
                            .addGroup(jPnlCargaLayout.createSequentialGroup()
                                .addGroup(jPnlCargaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jTxtPath)))
                    .addGroup(jPnlCargaLayout.createSequentialGroup()
                        .addGroup(jPnlCargaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPnlCargaLayout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(jButCargarPadron, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(82, 82, 82)
                                .addGroup(jPnlCargaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jButCancelCargAsync, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButCargarPadronAsync, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPnlCargaLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jPBarLoadFile, javax.swing.GroupLayout.PREFERRED_SIZE, 584, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 378, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPnlCargaLayout.setVerticalGroup(
            jPnlCargaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnlCargaLayout.createSequentialGroup()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTxtPath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTxtFileName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPnlCargaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButCargarPadron)
                    .addGroup(jPnlCargaLayout.createSequentialGroup()
                        .addComponent(jButCargarPadronAsync)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButCancelCargAsync)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 369, Short.MAX_VALUE)
                .addComponent(jPBarLoadFile, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Cargar Padrón", jPnlCarga);

        jButBuscar.setText("Buscar");
        jButBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButBuscarActionPerformed(evt);
            }
        });

        jLabel3.setText("Cédula:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTxtFldNumCedula, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jButBuscar)
                .addContainerGap(658, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtFldNumCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButBuscar)
                    .addComponent(jLabel3))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jTblSearch.addTab("Por Cédula", jPanel1);

        jLabel4.setText("Nombre:");

        jLabel5.setText("Prim.Apellido:");

        jLabel6.setText("Seg.Apellido:");

        jButBuscar1.setText("Buscar");
        jButBuscar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButBuscar1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jTxtFldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTxtFldPrimApe, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTxtFldSegApe, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButBuscar1)
                .addContainerGap(126, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTxtFldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jTxtFldSegApe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtFldPrimApe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButBuscar1))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jTblSearch.addTab("Por Nombre", jPanel2);

        jTblData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTblData);

        javax.swing.GroupLayout jPnlSearchLayout = new javax.swing.GroupLayout(jPnlSearch);
        jPnlSearch.setLayout(jPnlSearchLayout);
        jPnlSearchLayout.setHorizontalGroup(
            jPnlSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnlSearchLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPnlSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(jTblSearch))
                .addContainerGap())
        );
        jPnlSearchLayout.setVerticalGroup(
            jPnlSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnlSearchLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTblSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 444, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Buscar", jPnlSearch);

        jToolBar1.setRollover(true);

        jBtnExit.setText("Salir");
        jBtnExit.setFocusable(false);
        jBtnExit.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBtnExit.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jBtnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnExitActionPerformed(evt);
            }
        });
        jToolBar1.add(jBtnExit);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cargarPadron(String pathFile, String fname) throws SQLException, IOException, CommonDALExceptions {
        PadronElecBL pebl = new PadronElecBL();

        PadronElecBE pebe = new PadronElecBE();

        fname = pathFile + File.separator + fname;

        //  pebl.deleteAll();
        File fi = new File(fname);
        FileInputStream fis = new FileInputStream(fi);
        // Charset charset = Charset.forName("UTF-16");
        InputStreamReader isr = new InputStreamReader(fis, "UTF8");
        // String en = isr.getEncoding();
        try ( BufferedReader br = new BufferedReader(isr)) {
            String line;
            while ((line = br.readLine()) != null) {
                String[] scrap = line.split(",", 7);
                pebe.setCedula(scrap[0].trim());
                pebe.setCodElect(scrap[1].trim());
                pebe.setFecCaduca(scrap[2].trim());
                pebe.setNombre(scrap[4].trim());
                pebe.setApellido1(scrap[5].trim());
                pebe.setApellido2(scrap[6].trim());
                boolean existeCed = pebl.existe(pebe.getCedula());
                if (!existeCed) {
                    pebl.insertar(pebe);
                }
                // pebl.insertar(pebe);
            }
        } catch (Exception ex) {
            Logger.getLogger(JFrmLoadPadron2.class.getName()).log(Level.SEVERE, null, ex);
        }

        JOptionPane.showConfirmDialog(null, "Proceso Finalizado....!");

    }

    private void jButCargarPadronActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButCargarPadronActionPerformed
        try {
            cargarPadron(jTxtPath.getText(), jTxtFileName.getText());
        } catch (SQLException ex) {
            Logger.getLogger(JFrmLoadPadron2.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(JFrmLoadPadron2.class.getName()).log(Level.SEVERE, null, ex);
        } catch (CommonDALExceptions ex) {
            Logger.getLogger(JFrmLoadPadron2.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButCargarPadronActionPerformed

    private void jButBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButBuscarActionPerformed
        try {
            ArrayList<ParamAction> lstParams = new ArrayList<>();
            lstParams.add(new ParamAction("cedula", ParamAction.JavaTypes.STRING, jTxtFldNumCedula.getText()));
            AbstractTableModel utm = consultarPadron(lstParams);
            jTblData.setModel(utm);
        } catch (SQLException | CommonDALExceptions ex) {
            Logger.getLogger(JFrmLoadPadron2.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "Excepcion " + ex.getMessage());
        }

    }//GEN-LAST:event_jButBuscarActionPerformed

    private void jButCargarPadronAsyncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButCargarPadronAsyncActionPerformed

        if (!this.isStarted) {
            if (JOptionPane.showConfirmDialog(null, "¿Desea Ejecutar la carga?", "Confirmar",
                    JOptionPane.OK_CANCEL_OPTION) == JOptionPane.OK_OPTION) {
                jButCargarPadron.setEnabled(false);
                jButCancelCargAsync.setEnabled(true);
                ca = new CargadorArchivos(this, jPBarLoadFile, jTxtPath.getText(), jTxtFileName.getText());
                ca.execute();
            } else {
                JOptionPane.showMessageDialog(null, "Opcion cancelada!!!!");
            }
        }


    }//GEN-LAST:event_jButCargarPadronAsyncActionPerformed

    private void jButCancelCargAsyncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButCancelCargAsyncActionPerformed
        if (this.ca != null) {
            this.ca.cancel(true);
            jButCargarPadron.setEnabled(true);
        }

    }//GEN-LAST:event_jButCancelCargAsyncActionPerformed

    private void jButBuscar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButBuscar1ActionPerformed
        try {
            ArrayList<ParamAction> lstParams = new ArrayList<>();
            if (jTxtFldNombre.getText().length() > 0) {
                lstParams.add(new ParamAction("nombre", ParamAction.JavaTypes.STRING,
                        jTxtFldNombre.getText(), true));
            }

            if (jTxtFldPrimApe.getText().length() > 0) {
                lstParams.add(new ParamAction("primApe", ParamAction.JavaTypes.STRING,
                        jTxtFldPrimApe.getText(), true));
            }

            if (jTxtFldSegApe.getText().length() > 0) {
                lstParams.add(new ParamAction("segApe", ParamAction.JavaTypes.STRING,
                        jTxtFldSegApe.getText(), true));
            }

            AbstractTableModel utm = consultarPadron(lstParams);
            jTblData.setModel(utm);
        } catch (SQLException | CommonDALExceptions ex) {
            Logger.getLogger(JFrmLoadPadron2.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "Excepcion " + ex.getMessage());
        }
    }//GEN-LAST:event_jButBuscar1ActionPerformed

    private void jBtnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jBtnExitActionPerformed

    private AbstractTableModel consultarPadron(ArrayList<ParamAction> plstParams) throws SQLException, CommonDALExceptions {
        PadronElecBL pebl = new PadronElecBL();
        ArrayList<PadronElecBE> lstCatClte = pebl.listar(plstParams);
        PadronElecTableModel utm = new PadronElecTableModel(lstCatClte);
        return utm;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrmLoadPadron2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrmLoadPadron2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrmLoadPadron2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrmLoadPadron2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JFrmLoadPadron2 jfrm = new JFrmLoadPadron2();
                jfrm.setTitle("Cargar Padron");
                jfrm.setLocationRelativeTo(null);
                jfrm.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnExit;
    private javax.swing.JButton jButBuscar;
    private javax.swing.JButton jButBuscar1;
    private javax.swing.JButton jButCancelCargAsync;
    private javax.swing.JButton jButCargarPadron;
    private javax.swing.JButton jButCargarPadronAsync;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JProgressBar jPBarLoadFile;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPnlCarga;
    private javax.swing.JPanel jPnlSearch;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTblData;
    private javax.swing.JTabbedPane jTblSearch;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JTextField jTxtFileName;
    private javax.swing.JTextField jTxtFldNombre;
    private javax.swing.JTextField jTxtFldNumCedula;
    private javax.swing.JTextField jTxtFldPrimApe;
    private javax.swing.JTextField jTxtFldSegApe;
    private javax.swing.JTextField jTxtPath;
    // End of variables declaration//GEN-END:variables

    private void initMyComponents() {
        DIContainer.registerDataManager(GloblaConstants.MARIADBCONN);
        jTxtPath.setText("C:\\Users\\garfi\\Downloads\\padron_completo");
        jTxtFileName.setText("PADRON_COMPLETO.txt");
        this.isStarted = false;

    }

}
